### ISSUE TITLE
Handle window close event

### ISSUE THREAD

**Issue by adi-works** [cloud-elements/heimdall#3]
We are using this SDK and it turns out we can't reset the authentication process if it was interrupted (user closed authentication window). I'd expect `CE.createInstance` to handle that in its callback, but callback is never invoked unless authentication went as normal. Is there an undocumented API or a workaround to handle this?

**Comment by matttrice** [comment]
Hi Adi,
I had a solution for this [working locally](https://share.getcloudapp.com/rRungdQj) but for some reason its not working consistently.  Sometimes the event message posts, but not always and I haven't figured out why. 

Let me know if you have any suggestions. I did deployed the [msg-onunload](https://github.com/CloudElementsOpenLabs/heimdall/tree/msg-onunload)  branch to staging if you want to test it outh... though I had even less luck on staging.

**Comment by matttrice** [comment]
I made some progress on this today and deployed to staging. 
Heimdall will now send an `unloaded` message back to the parent callback for refreshes and Heimdall form closes. Also if the Heimdall form was submitted a `submitted` message will be sent. What I don't have working yet is detecting events past that. Once the redirect has occurred and the vendor form loads the window event listeners are not working even though it is the same window.

**Comment by matttrice** [comment]
@adi518 did you see my last message above? You can test the update on staging... don't have to setup locally.  Let me know if you have any questions.

**Comment by matttrice** [comment]
Looks like there is an issue with the basic auth form... its not returning properly. Oauth 1 and 2 do though. I'm looking into this.

**Comment by adi-works** [comment]
Yes, thanks. 👍
